# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    # -   id: trailing-whitespace
    # -   id: end-of-file-fixer
    -   id: check-json
        exclude: ampel/contrib/hu/test
    # -  id: pretty-format-json
    #    args: [--no-sort-keys, --autofix, --indent=2]
    #    exclude: ampel/contrib/hu/test
    -   id: check-ast
    -   id: check-added-large-files
fail_fast: true
