name: ci

on:
  push:
    branches:
      - main
      - dev
      - v*-dev
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        conda-channels: conda-forge
        python-version: '3.10'
    # - uses: actions/cache@v2
    #   id: cache
    #   with:
    #     path: ${{ env.CONDA }}
    #     key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}-py39
    - name: Set up conda env
      # if: steps.cache.outputs.cache-hit != true
      run: conda install -y sncosmo iminuit scipy numpy pandas
    - name: Install dependencies
      run: |
        cat conda-linux-64.lock | awk '/^# pip/ {print substr($0,7)}' > requirements.txt
        conda run -n test python -m pip install --no-deps -r requirements.txt
    - name: Install project
      run: |
        conda run -n test python -m pip install --no-deps -e .
    - run: |
        conda run -n test mypy --namespace-packages -p ampel
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        conda-channels: conda-forge
        python-version: '3.10'
    # - uses: actions/cache@v2
    #   id: cache
    #   with:
    #     path: ${{ env.CONDA }}
    #     key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}-py39
    - name: Install pip dependencies
      # if: steps.cache.outputs.cache-hit != true
      run: |
        cat conda-linux-64.lock | awk '/^# pip/ {print substr($0,7)}' > requirements.txt
        conda run -n test python -m pip install --no-deps -r requirements.txt
    - name: Install project
      run: |
        conda run -n test python -m pip install --no-deps -e .
    - run: |
        conda run -n test pytest --cov ampel

