name: ci

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        conda-channels: conda-forge
        python-version: 3.9
    # - uses: actions/cache@v2
    #   id: cache
    #   with:
    #     path: ${{ env.CONDA }}
    #     key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}-py39
    - name: Install dependencies
      # if: steps.cache.outputs.cache-hit != true
      run: |
        conda install --file conda-linux-64.lock
        python -m pip install -r dev-requirements.txt -e . 
    - run: |
        mypy --namespace-packages -p ampel
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: s-weigand/setup-conda@v1
      with:
        conda-channels: conda-forge
        python-version: 3.9
    # - uses: actions/cache@v2
    #   id: cache
    #   with:
    #     path: ${{ env.CONDA }}
    #     key: ${{ hashFiles('setup.py') }}-${{ hashFiles('dev-requirements.txt') }}-py39
    - name: Set up conda env
      # if: steps.cache.outputs.cache-hit != true
      run: conda install -y sncosmo iminuit scipy numpy pandas
    - name: Install dependencies
      run: |
        python -m pip install --upgrade --upgrade-strategy eager -r dev-requirements.txt -e .
    - run: |
        pytest --cov=ampel

