name: ci

on:
  push:
    branches:
      - main
      - poetry
  pull_request:
    branches:
      - main
      - poetry

jobs:
  mypy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install wheel mypy==0.910.0 types-requests types-pytz pytest -e .
    - run: mypy --namespace-packages -p ampel
  
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install wheel pytest pytest-mock pytest-cov -e .
    - run: pytest --cov=ampel

